let doadores=JSON.parse(localStorage.getItem("doadores"))||[];
let recebidas=JSON.parse(localStorage.getItem("recebidas"))||[];
let entregas=JSON.parse(localStorage.getItem("entregas"))||[];
let estoque=JSON.parse(localStorage.getItem("estoque"))||{};

function dataHoje(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function dataBR(d){if(!d)return"-";let p=d.split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:d}
function normalizar(s){return String(s??"").trim().toLowerCase().replace(/\s+/g," ")}
function nomeExibicao(s){return s.split(" ").filter(Boolean).map(p=>p.charAt(0).toUpperCase()+p.slice(1)).join(" ")}
function qtd(n){let x=Number(n);return Number.isInteger(x)?String(x):x.toFixed(2).replace(".",",")}
function esc(s){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function salvar(){localStorage.setItem("doadores",JSON.stringify(doadores));localStorage.setItem("recebidas",JSON.stringify(recebidas));localStorage.setItem("entregas",JSON.stringify(entregas));localStorage.setItem("estoque",JSON.stringify(estoque))}
function msg(text,error=false){let c=document.getElementById("toast-container"),t=document.createElement("div");t.className=error?"toast error":"toast";t.textContent=text;c.appendChild(t);setTimeout(()=>t.remove(),3000)}
function limparZero(){Object.keys(estoque).forEach(k=>{if(!estoque[k]||Number(estoque[k].quantidade)<=0)delete estoque[k]})}
function totalEstoque(){return Object.values(estoque).reduce((a,p)=>a+Number(p.quantidade||0),0)}

Object.keys(estoque).forEach(k=>{if(typeof estoque[k]==="number")estoque[k]={nome:k,quantidade:estoque[k],unidade:"unidades"}});
recebidas=recebidas.map(x=>({...x,id:x.id||Date.now()+Math.random(),unidade:x.unidade||"unidades",data:x.data||dataHoje()}));
entregas=entregas.map(x=>({...x,id:x.id||Date.now()+Math.random(),unidade:x.unidade||"unidades",data:x.data||dataHoje()}));
limparZero();salvar();

const descr={inicio:"Visão geral do controle de doações da instituição.",doadores:"Cadastro e consulta dos doadores.",recebidas:"Registro das doações recebidas pela instituição.",entregas:"Registro dos produtos entregues às famílias atendidas.",estoque:"Controle dos produtos disponíveis.",relatorios:"Resumo das movimentações e do estoque."};
function abrir(p){document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===p));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active-page"));document.getElementById(p).classList.add("active-page");let b=document.querySelector(`[data-page="${p}"]`);document.getElementById("page-title").textContent=b?b.textContent:"Início";document.getElementById("page-description").textContent=descr[p]||"";if(p==="inicio")dashboard();if(p==="recebidas")preencherDoadores();if(p==="entregas")preencherProdutos()}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>abrir(b.dataset.page));
document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>abrir(b.dataset.go));

const formD=document.getElementById("form-doador");
formD.onsubmit=e=>{e.preventDefault();let nome=document.getElementById("doador-nome").value.trim(),cont=document.getElementById("doador-contato").value.trim();if(!nome)return msg("Informe o nome do doador.",true);if(doadores.some(d=>normalizar(d.nome)===normalizar(nome)))return msg("Esse doador já está cadastrado.",true);doadores.push({id:Date.now(),nome,contato:cont});salvar();formD.reset();doadoresView();preencherDoadores();resumo();msg("Doador cadastrado com sucesso.")};
function doacoesDoador(id){return recebidas.filter(x=>String(x.doadorId)===String(id)).length}
function doadoresView(){let q=normalizar(document.getElementById("busca-doador").value),a=doadores.filter(d=>normalizar(d.nome).includes(q)),l=document.getElementById("lista-doadores");if(!a.length)return l.innerHTML='<p class="empty">Nenhum doador encontrado.</p>';l.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Nome</th><th>Contato</th><th>Doações realizadas</th><th>Ações</th></tr></thead><tbody>${a.map(d=>`<tr><td class="item-name">${esc(d.nome)}</td><td>${esc(d.contato||"Não informado")}</td><td>${doacoesDoador(d.id)}</td><td><button class="action-btn" onclick="editarDoador(${d.id})">Editar</button><button class="action-btn delete" onclick="excluirDoador(${d.id})">Excluir</button></td></tr>`).join("")}</tbody></table></div>`}
document.getElementById("busca-doador").oninput=doadoresView;
function editarDoador(id){let d=doadores.find(x=>String(x.id)===String(id));if(!d)return;document.getElementById("editar-id").value=d.id;document.getElementById("editar-nome").value=d.nome;document.getElementById("editar-contato").value=d.contato||"";document.getElementById("modal-editar").classList.add("show")}
function fechar(){document.getElementById("modal-editar").classList.remove("show")}
document.getElementById("fechar-modal").onclick=fechar;document.getElementById("cancelar-modal").onclick=fechar;
document.getElementById("modal-editar").onclick=e=>{if(e.target.id==="modal-editar")fechar()};
document.getElementById("form-editar-doador").onsubmit=e=>{e.preventDefault();let id=document.getElementById("editar-id").value,n=document.getElementById("editar-nome").value.trim(),c=document.getElementById("editar-contato").value.trim();if(!n)return msg("Informe o nome do doador.",true);if(doadores.some(d=>String(d.id)!==String(id)&&normalizar(d.nome)===normalizar(n)))return msg("Já existe outro doador com esse nome.",true);let d=doadores.find(x=>String(x.id)===String(id));if(!d)return;d.nome=n;d.contato=c;recebidas.forEach(x=>{if(String(x.doadorId)===String(id))x.doador=n});salvar();doadoresView();preencherDoadores();mostrarRecebidas();fechar();msg("Doador atualizado com sucesso.")};
function excluirDoador(id){if(recebidas.some(x=>String(x.doadorId)===String(id)))return msg("Não é possível excluir um doador que possui doações registradas.",true);let d=doadores.find(x=>String(x.id)===String(id));if(!d||!confirm(`Excluir o doador "${d.nome}"?`))return;doadores=doadores.filter(x=>String(x.id)!==String(id));salvar();doadoresView();preencherDoadores();resumo();msg("Doador excluído.")}
function preencherDoadores(){let s=document.getElementById("rec-doador"),v=s.value;s.innerHTML='<option value="">Selecione o doador</option>';doadores.slice().sort((a,b)=>a.nome.localeCompare(b.nome)).forEach(d=>{let o=document.createElement("option");o.value=d.id;o.textContent=d.nome;s.appendChild(o)});if([...s.options].some(o=>o.value===v))s.value=v}

document.getElementById("form-recebida").onsubmit=e=>{e.preventDefault();let did=document.getElementById("rec-doador").value,n=document.getElementById("rec-item").value.trim(),q=Number(document.getElementById("rec-qtd").value),u=document.getElementById("rec-unidade").value,d=document.getElementById("rec-data").value;if(!did)return msg("Selecione um doador.",true);if(!n)return msg("Informe o produto.",true);if(!Number.isFinite(q)||q<=0)return msg("Informe uma quantidade maior que zero.",true);if(!u)return msg("Selecione a unidade.",true);if(!d)return msg("Informe a data.",true);let key=normalizar(n),don=doadores.find(x=>String(x.id)===String(did));if(!don)return msg("Doador não encontrado.",true);if(estoque[key]&&estoque[key].unidade!==u)return msg(`O produto já está cadastrado como "${estoque[key].unidade}". Use a mesma unidade.`,true);recebidas.push({id:Date.now(),doadorId:don.id,doador:don.nome,item:nomeExibicao(n),quantidade:q,unidade:u,data:d});if(estoque[key])estoque[key].quantidade+=q;else estoque[key]={nome:nomeExibicao(n),quantidade:q,unidade:u};salvar();e.target.reset();document.getElementById("rec-data").value=dataHoje();mostrarRecebidas();mostrarEstoque();preencherProdutos();dashboard();relatorios();msg("Doação registrada e estoque atualizado.")};
function mostrarRecebidas(){let q=normalizar(document.getElementById("busca-recebida").value),a=recebidas.slice().reverse().filter(x=>normalizar(`${x.doador} ${x.item} ${x.unidade}`).includes(q)),l=document.getElementById("lista-recebidas");if(!a.length)return l.innerHTML='<p class="empty">Nenhuma doação recebida encontrada.</p>';l.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Doador</th><th>Produto</th><th>Quantidade</th><th>Ações</th></tr></thead><tbody>${a.map(x=>`<tr><td>${dataBR(x.data)}</td><td>${esc(x.doador)}</td><td class="item-name">${esc(x.item)}</td><td>${qtd(x.quantidade)} ${esc(x.unidade)}</td><td><button class="action-btn delete" onclick="excluirRecebida(${x.id})">Excluir</button></td></tr>`).join("")}</tbody></table></div>`}
document.getElementById("busca-recebida").oninput=mostrarRecebidas;
function excluirRecebida(id){let d=recebidas.find(x=>String(x.id)===String(id));if(!d)return;let p=estoque[normalizar(d.item)];if(!p||p.quantidade<d.quantidade)return msg("Essa doação não pode ser excluída porque a quantidade já foi utilizada.",true);if(!confirm("Excluir esta doação e ajustar o estoque?"))return;p.quantidade-=d.quantidade;recebidas=recebidas.filter(x=>String(x.id)!==String(id));limparZero();salvar();mostrarRecebidas();mostrarEstoque();preencherProdutos();dashboard();relatorios();msg("Doação excluída e estoque ajustado.")}

function mostrarEstoque(){limparZero();let q=normalizar(document.getElementById("busca-estoque").value),a=Object.values(estoque).filter(p=>p.quantidade>0&&normalizar(p.nome).includes(q)).sort((a,b)=>a.nome.localeCompare(b.nome)),l=document.getElementById("lista-estoque");if(!a.length)return l.innerHTML='<p class="empty">Nenhum produto disponível no estoque.</p>';l.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Produto</th><th>Quantidade</th><th>Unidade</th><th>Situação</th></tr></thead><tbody>${a.map(p=>`<tr><td class="item-name">${esc(p.nome)}</td><td>${qtd(p.quantidade)}</td><td>${esc(p.unidade)}</td><td><span class="status ${p.quantidade<=3?"low":"ok"}">${p.quantidade<=3?"Estoque baixo":"Disponível"}</span></td></tr>`).join("")}</tbody></table></div>`;salvar()}
document.getElementById("busca-estoque").oninput=mostrarEstoque;
function preencherProdutos(){let s=document.getElementById("ent-item"),v=s.value;s.innerHTML='<option value="">Selecione o produto</option>';Object.entries(estoque).filter(([,p])=>p.quantidade>0).sort((a,b)=>a[1].nome.localeCompare(b[1].nome)).forEach(([k,p])=>{let o=document.createElement("option");o.value=k;o.textContent=`${p.nome} - ${qtd(p.quantidade)} ${p.unidade} disponíveis`;s.appendChild(o)});if([...s.options].some(o=>o.value===v))s.value=v}

document.getElementById("form-entrega").onsubmit=e=>{e.preventDefault();let f=document.getElementById("ent-familia").value.trim(),k=document.getElementById("ent-item").value,q=Number(document.getElementById("ent-qtd").value),d=document.getElementById("ent-data").value;if(!f)return msg("Informe a família atendida.",true);if(!k||!estoque[k])return msg("Selecione um produto disponível.",true);if(!Number.isFinite(q)||q<=0)return msg("Informe uma quantidade maior que zero.",true);if(!d)return msg("Informe a data.",true);let p=estoque[k];if(q>p.quantidade)return msg(`Quantidade insuficiente. Há apenas ${qtd(p.quantidade)} ${p.unidade} disponíveis.`,true);entregas.push({id:Date.now(),familia:f,item:p.nome,chave:k,quantidade:q,unidade:p.unidade,data:d});p.quantidade-=q;limparZero();salvar();e.target.reset();document.getElementById("ent-data").value=dataHoje();mostrarEntregas();mostrarEstoque();preencherProdutos();dashboard();relatorios();msg("Entrega registrada e estoque atualizado.")};
function mostrarEntregas(){let q=normalizar(document.getElementById("busca-entrega").value),a=entregas.slice().reverse().filter(x=>normalizar(`${x.familia} ${x.item} ${x.unidade}`).includes(q)),l=document.getElementById("lista-entregas");if(!a.length)return l.innerHTML='<p class="empty">Nenhuma entrega encontrada.</p>';l.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Família atendida</th><th>Produto</th><th>Quantidade</th><th>Ações</th></tr></thead><tbody>${a.map(x=>`<tr><td>${dataBR(x.data)}</td><td>${esc(x.familia)}</td><td class="item-name">${esc(x.item)}</td><td>${qtd(x.quantidade)} ${esc(x.unidade)}</td><td><button class="action-btn delete" onclick="excluirEntrega(${x.id})">Excluir</button></td></tr>`).join("")}</tbody></table></div>`}
document.getElementById("busca-entrega").oninput=mostrarEntregas;
function excluirEntrega(id){let x=entregas.find(e=>String(e.id)===String(id));if(!x||!confirm("Excluir esta entrega e devolver a quantidade ao estoque?"))return;let k=x.chave||normalizar(x.item);if(estoque[k])estoque[k].quantidade+=x.quantidade;else estoque[k]={nome:x.item,quantidade:x.quantidade,unidade:x.unidade};entregas=entregas.filter(e=>String(e.id)!==String(id));salvar();mostrarEntregas();mostrarEstoque();preencherProdutos();dashboard();relatorios();msg("Entrega excluída e estoque atualizado.")}

function resumo(){document.getElementById("total-doadores").textContent=doadores.length;document.getElementById("total-recebidas").textContent=recebidas.length;document.getElementById("total-entregas").textContent=entregas.length;document.getElementById("total-estoque").textContent=qtd(totalEstoque())}
function dashboard(){resumo();let es=Object.values(estoque).filter(p=>p.quantidade>0).sort((a,b)=>a.nome.localeCompare(b.nome)).slice(0,6),l=document.getElementById("dashboard-estoque");l.innerHTML=es.length?es.map(p=>`<div class="movement"><div><strong>${esc(p.nome)}</strong><small>${qtd(p.quantidade)} ${esc(p.unidade)}</small></div><span class="movement-type ${p.quantidade<=3?"delivered":"received"}">${p.quantidade<=3?"ESTOQUE BAIXO":"DISPONÍVEL"}</span></div>`).join(""):'<p class="empty">Nenhum produto disponível no momento.</p>';let m=recebidas.map(x=>({tipo:"received",data:x.data,text:`Doação recebida — ${x.item}`,det:`${qtd(x.quantidade)} ${x.unidade} • ${x.doador}`})).concat(entregas.map(x=>({tipo:"delivered",data:x.data,text:`Doação entregue — ${x.item}`,det:`${qtd(x.quantidade)} ${x.unidade} • ${x.familia}`}))).sort((a,b)=>b.data.localeCompare(a.data)).slice(0,6),lm=document.getElementById("dashboard-movimentacoes");lm.innerHTML=m.length?m.map(x=>`<div class="movement"><div><strong>${esc(x.text)}</strong><small>${esc(x.det)} • ${dataBR(x.data)}</small></div><span class="movement-type ${x.tipo}">${x.tipo==="received"?"ENTRADA":"SAÍDA"}</span></div>`).join(""):'<p class="empty">Nenhuma movimentação registrada.</p>'}
function relatorios(){document.getElementById("rel-total-recebidas").textContent=recebidas.length;document.getElementById("rel-total-entregas").textContent=entregas.length;let ps=Object.values(estoque).filter(p=>p.quantidade>0);document.getElementById("rel-produtos").textContent=ps.length;document.getElementById("rel-itens").textContent=qtd(totalEstoque());let r={};recebidas.forEach(x=>{let k=normalizar(x.item);r[k]??={nome:x.item,unidade:x.unidade,recebido:0,entregue:0,estoque:0};r[k].recebido+=Number(x.quantidade)||0});entregas.forEach(x=>{let k=x.chave||normalizar(x.item);r[k]??={nome:x.item,unidade:x.unidade,recebido:0,entregue:0,estoque:0};r[k].entregue+=Number(x.quantidade)||0});Object.entries(estoque).forEach(([k,p])=>{r[k]??={nome:p.nome,unidade:p.unidade,recebido:0,entregue:0,estoque:0};r[k].estoque=p.quantidade});let a=Object.values(r).filter(x=>x.recebido||x.entregue||x.estoque).sort((a,b)=>a.nome.localeCompare(b.nome)),l=document.getElementById("lista-relatorios");l.innerHTML=a.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Produto</th><th>Recebido</th><th>Entregue</th><th>Disponível</th></tr></thead><tbody>${a.map(x=>`<tr><td class="item-name">${esc(x.nome)}</td><td>${qtd(x.recebido)} ${esc(x.unidade)}</td><td>${qtd(x.entregue)} ${esc(x.unidade)}</td><td>${qtd(x.estoque)} ${esc(x.unidade)}</td></tr>`).join("")}</tbody></table></div>`:'<p class="empty">Ainda não há dados suficientes para o relatório.</p>'}

document.getElementById("rec-data").value=dataHoje();document.getElementById("ent-data").value=dataHoje();preencherDoadores();doadoresView();mostrarRecebidas();mostrarEstoque();mostrarEntregas();preencherProdutos();resumo();dashboard();relatorios();
